date_tags = [
    'date/time of service',
    'date of procedure',
    'registration date',
    'dt/tm of service',
    'servie date/time',
    'dates of service',
    'date of service',
    'procedure date',
    'discharge date',
    'service dates',
    'dt of service',
    'service dt/tm',
    'service date',
    'request date',
    'order dt/tm',
    'dischg date',
    'service dt',
    'admit date',
    'start date',
    'order date',
    'exam date',
    'admit dt',
    'adm date',
    'end date',
    'dis date',
    'dis dt',
    'dos',
    'adm',
    'd/c',
    'discharge/service',
    'admission date',
    'admitted',
    'visit date',
    'date of visit',
    'service_date',
    'EFF DATE',
    'ADM DATE',
    'RUN DATE',
    'DRG STATUS DATE',
    'ABS STATUS DATE',
    'Date of admission',
    'Observation Start Date',
    'Discharge date',
    'DATE OF ADMISSION',
    'DATE OF DISCHARGE',
    'Visit Date',
    'DATE OF CONSULTATION',
    'Hospital course to date',
    'Run Date Time',
    'Date Run',
    'Order Date',
    'Date of Birth',
    'Oper Date',
    'Last Updated',
    'Last solids date',
    'Last liquids date',
    'Completed Date',
    'expiration date',
    'Study Date',
    'ADMIT DATE',
    'Activity Date',
    'Date of last dressing change',
    'Admit Date Time',
    'Result Date',
    'Date of Visit',
    'Admission Date',
    'Date of Onset',
    'Transfusion Date',
    'Evaluation Date',
    'EXPIRATION DATE',
    'DATE AND TIME',
    'Performance Date',
    'Requesting Date',
    'Date of Collection',
    'Requested Date',
    'Date Written',
    'Collect Date',
    'Receipt Date',
    'Procedure Date',
    'Date of Study',
    'Arrival Date',
    'Triage Date',
    'CONSULTATION DATE',
    'Date of birth',
    'DOB',
    "printed", "generated",
    "printed by",
    'added by',
    'addendum',
    'addendum by',
    'authenticated by',
    'consults by',
    'edited by',
    'electronically signed',
    'electronically witnessed',
    'perform',
    'review by',
    'reviewed by',
    'sign by',
    'signed by',
    'signed on',
    'transcribe by',
    'transcribv by',
    'verify by']
adm_dis_tag = ['discharge date',
               'dischg date',
               'admit date',
               'admit dt',
               'adm date',
               'dis date',
               'dis dt',
               'adm',
               'discharge/service',
               'admission date',
               'admitted',
               'Date of admission']
suppress_date_tag_Section_end = [
    'registration date',
    'discharge date',
    'dischg date',
    'admit date',
    'admit dt',
    'adm date',
    'dis date',
    'dis dt',
    'adm',
    'd/c',
    'discharge/service',
    'admission date',
    'admitted',
    'visit date',
    'date of visit',
    'EFF DATE',
    'ADM DATE',
    'Date of admission',
    'Discharge date',
    'DATE OF ADMISSION',
    'DATE OF DISCHARGE',
    'Visit Date',
    'Date of Birth',
    'ADMIT DATE',
    'Admit Date Time',
    'Date of Visit',
    'Admission Date',
    'Arrival Date',
    'Date of birth',
    'DOB',
    "printed", "generated",]

suppress_date_tag_section = [ 
            # 'date/time of service',
            # 'date of procedure',
            # 'registration date',
            # 'dt/tm of service',
            # 'servie date/time',
            # 'dates of service',
            # 'date of service',
            # 'procedure date',
            'discharge date',
            # 'service dates',
            # 'dt of service',
            # 'service dt/tm',
            # 'service date',
            # 'request date',
            # 'order dt/tm',
            'dischg date',
            # 'service dt',
            # 'admit date',
            # 'start date',
            # 'order date',
            # 'exam date',
            # 'admit dt',
            # 'adm date',
            'end date',
            'dis date',
            'dis dt',
            # 'dos:',
            # 'adm:',
            # 'd/c:',
            'discharge/service',
            'admission date',
            # 'admitted',
            # 'visit date',
            # 'date of visit',
            # 'service_date',
            # 'EFF DATE',
            # 'ADM DATE',
            # 'RUN DATE',
            # 'DRG STATUS DATE',
            # 'ABS STATUS DATE',
            'Date of admission:',
            # 'Observation Start Date',
            'Discharge date',
            # 'DATE OF ADMISSION',
            'DATE OF DISCHARGE',
            # 'Visit Date',
            # 'DATE OF CONSULTATION',
            # 'Hospital course to date',
            # 'Run Date Time',
            # 'Date Run',
            # 'Order Date',
            'Date of Birth',
            # 'Oper Date',
            # 'Last Updated',
            # 'Last solids date',
            # 'Last liquids date',
            'Completed Date',
            'expiration date',
            # 'Study Date',
            # 'ADMIT DATE',
            # 'Activity Date',
            # 'Date of last dressing change',
            # 'Admit Date Time',
            # 'Result Date',
            # 'Date of Visit',
            # 'Admission Date',
            # 'Date of Onset',
            # 'Transfusion Date',
            # 'Evaluation Date',
            'EXPIRATION DATE',
            # 'DATE AND TIME',
            # 'Performance Date',
            # 'Requesting Date',
            # 'Date of Collection',
            # 'Requested Date',
            # 'Date Written',
            # 'Collect Date',
            # 'Receipt Date',
            # 'Procedure Date',
            # 'Date of Study',
            # 'Arrival Date',
            # 'Triage Date',
            # 'CONSULTATION DATE',
            'Date of birth',
            'DOB',
            "printed", 
            
            'added by',
            'addendum',
            'addendum by',
            'authenticated by',
            'consults by',
            'edited by',
            'electronically signed',
            'electronically witnessed',
            'perform',
            'review by',
            'reviewed by',
            'sign by',
            'signed by',
            'signed on',
            'transcribe by',
            'transcribv by',
            'verify by']